# Generated by Django 2.2.11 on 2020-03-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='workers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('otch', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=1)),
                ('date', models.DateField()),
                ('adres', models.CharField(max_length=60)),
                ('ed', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=40)),
                ('spec', models.CharField(max_length=20)),
                ('stage', models.IntegerField()),
                ('add_abil', models.CharField(max_length=255)),
                ('reasons', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
