# Generated by Django 2.2.11 on 2020-03-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200324_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workers',
            name='sex',
            field=models.CharField(max_length=20),
        ),
    ]
