# Generated by Django 2.2.11 on 2020-03-27 12:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200324_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='spec',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('conditions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('price', models.IntegerField()),
                ('id_spec', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='workers',
            name='adres',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='workers',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='workers',
            name='ed',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='workers',
            name='fam',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='workers',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='workers',
            name='school',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='workers',
            name='spec',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='workers',
            name='stage',
            field=models.IntegerField(blank=True),
        ),
    ]
